export interface MentorParams {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  institution: string | null;
  degree: string;
  expertise: string[];
  bio: string | null;
  max_students?: number;
  created_at?: string;
  updated_at?: string;
}

export class Mentor {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  institution: string | null;
  degree: string;
  expertise: string[];
  bio: string | null;
  max_students: number;
  created_at: string;
  updated_at: string;

  constructor(params: MentorParams) {
    this.id = params.id;
    this.user_id = params.user_id;
    this.full_name = params.full_name;
    this.email = params.email;
    this.institution = params.institution;
    this.degree = params.degree;
    this.expertise = params.expertise;
    this.bio = params.bio;
    this.max_students = params.max_students ?? 5;
    this.created_at = params.created_at ?? new Date().toISOString();
    this.updated_at = params.updated_at ?? this.created_at;
  }
}

export const mentorExamples = [
  new Mentor({
    id: "mentor-01",
    user_id: "user-mentor-01",
    full_name: "Dr. Elena Rossi",
    email: "elena.rossi@epfl.ch",
    institution: "EPFL",
    degree: "Doctorat",
    expertise: ["Human-Computer Interaction", "AI Ethics", "Qualitative Research"],
    bio: "Research mentor focused on user-centered AI systems and thesis framing.",
    max_students: 6,
    created_at: "2026-03-01T09:00:00.000Z",
    updated_at: "2026-03-01T09:00:00.000Z",
  }),
  new Mentor({
    id: "mentor-02",
    user_id: "user-mentor-02",
    full_name: "Marc Dubois",
    email: "marc.dubois@unil.ch",
    institution: "UNIL",
    degree: "Master",
    expertise: ["Machine Learning", "Data Visualization", "Statistics"],
    bio: "Supports students who need help structuring experiments and communicating results.",
    max_students: 4,
    created_at: "2026-03-02T10:30:00.000Z",
    updated_at: "2026-03-02T10:30:00.000Z",
  }),
  new Mentor({
    id: "mentor-03",
    user_id: "user-mentor-03",
    full_name: "Sofia Meyer",
    email: "sofia.meyer@idiap.ch",
    institution: "Idiap Research Institute",
    degree: "Doctorat",
    expertise: ["Natural Language Processing", "Academic Writing", "Literature Review"],
    bio: "Helps students turn scattered ideas into a clear research question and writing plan.",
    max_students: 5,
    created_at: "2026-03-03T14:15:00.000Z",
    updated_at: "2026-03-03T14:15:00.000Z",
  }),
  new Mentor({
    id: "mentor-04",
    user_id: "user-mentor-04",
    full_name: "Anna Keller",
    email: "anna.keller@ethz.ch",
    institution: "ETH Zurich",
    degree: "Doctorat",
    expertise: ["Computer Vision", "Deep Learning", "Robotics"],
    bio: "Guides students working on perception systems and applied AI prototypes.",
    max_students: 4,
    created_at: "2026-03-04T08:30:00.000Z",
    updated_at: "2026-03-04T08:30:00.000Z",
  }),
  new Mentor({
    id: "mentor-05",
    user_id: "user-mentor-05",
    full_name: "Thomas Weber",
    email: "thomas.weber@epfl.ch",
    institution: "EPFL",
    degree: "Doctorat",
    expertise: ["Data Science", "Causal Inference", "Experiment Design"],
    bio: "Helps students structure experiments and extract reliable conclusions from data.",
    max_students: 6,
    created_at: "2026-03-05T09:10:00.000Z",
    updated_at: "2026-03-05T09:10:00.000Z",
  }),
  new Mentor({
    id: "mentor-06",
    user_id: "user-mentor-06",
    full_name: "Laura Schmidt",
    email: "laura.schmidt@uzh.ch",
    institution: "University of Zurich",
    degree: "Master",
    expertise: ["Digital Health", "UX Research", "Service Design"],
    bio: "Supports thesis work at the intersection of healthcare services and user research.",
    max_students: 5,
    created_at: "2026-03-06T11:45:00.000Z",
    updated_at: "2026-03-06T11:45:00.000Z",
  }),
  new Mentor({
    id: "mentor-07",
    user_id: "user-mentor-07",
    full_name: "David Morel",
    email: "david.morel@unil.ch",
    institution: "UNIL",
    degree: "Doctorat",
    expertise: ["Behavioral Science", "Survey Design", "Quantitative Methods"],
    bio: "Works with students on research design, surveys, and evidence-driven reporting.",
    max_students: 7,
    created_at: "2026-03-07T10:20:00.000Z",
    updated_at: "2026-03-07T10:20:00.000Z",
  }),
  new Mentor({
    id: "mentor-08",
    user_id: "user-mentor-08",
    full_name: "Claire Martin",
    email: "claire.martin@unisg.ch",
    institution: "University of St. Gallen (HSG)",
    degree: "Master",
    expertise: ["Innovation Management", "Strategy", "Entrepreneurship"],
    bio: "Mentors applied projects that connect research with product or business strategy.",
    max_students: 5,
    created_at: "2026-03-08T13:00:00.000Z",
    updated_at: "2026-03-08T13:00:00.000Z",
  }),
  new Mentor({
    id: "mentor-09",
    user_id: "user-mentor-09",
    full_name: "Julien Perrin",
    email: "julien.perrin@idiap.ch",
    institution: "Idiap Research Institute",
    degree: "Doctorat",
    expertise: ["Speech Processing", "NLP", "Research Engineering"],
    bio: "Helps students bridge academic ideas and working machine learning systems.",
    max_students: 4,
    created_at: "2026-03-09T15:40:00.000Z",
    updated_at: "2026-03-09T15:40:00.000Z",
  }),
  new Mentor({
    id: "mentor-10",
    user_id: "user-mentor-10",
    full_name: "Sarah Nguyen",
    email: "sarah.nguyen@epfl.ch",
    institution: "EPFL",
    degree: "Doctorat",
    expertise: ["Human-Centered AI", "Interaction Design", "Prototyping"],
    bio: "Supports students designing AI tools that need clear, testable user value.",
    max_students: 6,
    created_at: "2026-03-10T08:50:00.000Z",
    updated_at: "2026-03-10T08:50:00.000Z",
  }),
  new Mentor({
    id: "mentor-11",
    user_id: "user-mentor-11",
    full_name: "Nicolas Rey",
    email: "nicolas.rey@uzh.ch",
    institution: "University of Zurich",
    degree: "Doctorat",
    expertise: ["Ethics", "Technology Policy", "Responsible Innovation"],
    bio: "Advises students exploring social impact, governance, and ethics in technology.",
    max_students: 5,
    created_at: "2026-03-11T09:35:00.000Z",
    updated_at: "2026-03-11T09:35:00.000Z",
  }),
  new Mentor({
    id: "mentor-12",
    user_id: "user-mentor-12",
    full_name: "Maya Johnson",
    email: "maya.johnson@ethz.ch",
    institution: "ETH Zurich",
    degree: "Doctorat",
    expertise: ["Systems Design", "Cybersecurity", "Software Architecture"],
    bio: "Works with students who need help structuring technical systems and secure prototypes.",
    max_students: 3,
    created_at: "2026-03-12T12:15:00.000Z",
    updated_at: "2026-03-12T12:15:00.000Z",
  }),
  new Mentor({
    id: "mentor-13",
    user_id: "user-mentor-13",
    full_name: "Paul Girard",
    email: "paul.girard@epfl.ch",
    institution: "EPFL",
    degree: "Master",
    expertise: ["Sustainability", "Energy Systems", "Data Modeling"],
    bio: "Supports projects focused on sustainability metrics, energy transitions, and modeling.",
    max_students: 4,
    created_at: "2026-03-13T10:00:00.000Z",
    updated_at: "2026-03-13T10:00:00.000Z",
  }),
  new Mentor({
    id: "mentor-14",
    user_id: "user-mentor-14",
    full_name: "Isabelle Fournier",
    email: "isabelle.fournier@unibe.ch",
    institution: "University of Bern",
    degree: "Doctorat",
    expertise: ["Qualitative Research", "Interview Analysis", "Field Studies"],
    bio: "Helps students sharpen research questions and turn field notes into strong insights.",
    max_students: 6,
    created_at: "2026-03-14T09:25:00.000Z",
    updated_at: "2026-03-14T09:25:00.000Z",
  }),
  new Mentor({
    id: "mentor-15",
    user_id: "user-mentor-15",
    full_name: "Liam Cooper",
    email: "liam.cooper@ost.ch",
    institution: "OST - Eastern Switzerland University of Applied Sciences",
    degree: "Master",
    expertise: ["Scientific Computing", "Data Pipelines", "Visualization"],
    bio: "Mentors technically demanding projects involving data infrastructure and analysis.",
    max_students: 4,
    created_at: "2026-03-15T14:05:00.000Z",
    updated_at: "2026-03-15T14:05:00.000Z",
  }),
  new Mentor({
    id: "mentor-16",
    user_id: "user-mentor-16",
    full_name: "Emma Laurent",
    email: "emma.laurent@fhnw.ch",
    institution: "FHNW",
    degree: "Master",
    expertise: ["Product Design", "User Testing", "Accessibility"],
    bio: "Supports student teams building inclusive products with rigorous usability validation.",
    max_students: 5,
    created_at: "2026-03-16T08:40:00.000Z",
    updated_at: "2026-03-16T08:40:00.000Z",
  }),
  new Mentor({
    id: "mentor-17",
    user_id: "user-mentor-17",
    full_name: "Robin Fischer",
    email: "robin.fischer@zhaw.ch",
    institution: "ZHAW",
    degree: "Doctorat",
    expertise: ["Applied AI", "MLOps", "Model Evaluation"],
    bio: "Helps students take AI projects from notebook prototypes to robust evaluations.",
    max_students: 5,
    created_at: "2026-03-17T11:20:00.000Z",
    updated_at: "2026-03-17T11:20:00.000Z",
  }),
  new Mentor({
    id: "mentor-18",
    user_id: "user-mentor-18",
    full_name: "Camille Blanc",
    email: "camille.blanc@unibas.ch",
    institution: "University of Basel",
    degree: "Doctorat",
    expertise: ["Bioinformatics", "Statistics", "Reproducible Research"],
    bio: "Advises students on reproducibility, statistical rigor, and scientific workflows.",
    max_students: 4,
    created_at: "2026-03-18T13:55:00.000Z",
    updated_at: "2026-03-18T13:55:00.000Z",
  }),
  new Mentor({
    id: "mentor-19",
    user_id: "user-mentor-19",
    full_name: "Kevin Muller",
    email: "kevin.muller@epfl.ch",
    institution: "EPFL",
    degree: "Master",
    expertise: ["Computer Graphics", "Visualization", "Interactive Systems"],
    bio: "Supports interactive visualization and interface-heavy thesis projects.",
    max_students: 6,
    created_at: "2026-03-19T09:45:00.000Z",
    updated_at: "2026-03-19T09:45:00.000Z",
  }),
  new Mentor({
    id: "mentor-20",
    user_id: "user-mentor-20",
    full_name: "Olivia Grant",
    email: "olivia.grant@usi.ch",
    institution: "USI - Universita della Svizzera italiana",
    degree: "Doctorat",
    expertise: ["Public Policy", "Digital Governance", "Writing"],
    bio: "Helps students transform complex policy topics into well-structured thesis narratives.",
    max_students: 5,
    created_at: "2026-03-20T10:30:00.000Z",
    updated_at: "2026-03-20T10:30:00.000Z",
  }),
  new Mentor({
    id: "mentor-21",
    user_id: "user-mentor-21",
    full_name: "Hugo Bernard",
    email: "hugo.bernard@unibe.ch",
    institution: "University of Bern",
    degree: "Master",
    expertise: ["Economics", "Forecasting", "Data Analysis"],
    bio: "Advises students who need strong analytical framing and quantitative storytelling.",
    max_students: 7,
    created_at: "2026-03-21T12:00:00.000Z",
    updated_at: "2026-03-21T12:00:00.000Z",
  }),
  new Mentor({
    id: "mentor-22",
    user_id: "user-mentor-22",
    full_name: "Chloe Steiner",
    email: "chloe.steiner@zhaw.ch",
    institution: "ZHAW",
    degree: "Master",
    expertise: ["Education Technology", "Learning Design", "Evaluation"],
    bio: "Supports research on learning experiences, educational tools, and impact assessment.",
    max_students: 5,
    created_at: "2026-03-22T08:15:00.000Z",
    updated_at: "2026-03-22T08:15:00.000Z",
  }),
  new Mentor({
    id: "mentor-23",
    user_id: "user-mentor-23",
    full_name: "Victor Salvi",
    email: "victor.salvi@usi.ch",
    institution: "USI - Universita della Svizzera italiana",
    degree: "Doctorat",
    expertise: ["Software Engineering", "Developer Tools", "Empirical Studies"],
    bio: "Works with students on engineering methods, tooling, and measurable developer outcomes.",
    max_students: 4,
    created_at: "2026-03-23T15:10:00.000Z",
    updated_at: "2026-03-23T15:10:00.000Z",
  }),
  new Mentor({
    id: "mentor-24",
    user_id: "user-mentor-24",
    full_name: "Lea Dubret",
    email: "lea.dubret@epfl.ch",
    institution: "EPFL",
    degree: "Doctorat",
    expertise: ["Climate Tech", "Systems Thinking", "Stakeholder Research"],
    bio: "Supports interdisciplinary thesis work involving sustainability and complex systems.",
    max_students: 5,
    created_at: "2026-03-24T09:00:00.000Z",
    updated_at: "2026-03-24T09:00:00.000Z",
  }),
  new Mentor({
    id: "mentor-25",
    user_id: "user-mentor-25",
    full_name: "Jonas Hartmann",
    email: "jonas.hartmann@ethz.ch",
    institution: "ETH Zurich",
    degree: "Doctorat",
    expertise: ["Optimization", "Operations Research", "Simulation"],
    bio: "Helps students model decision problems and compare algorithmic alternatives.",
    max_students: 4,
    created_at: "2026-03-25T10:50:00.000Z",
    updated_at: "2026-03-25T10:50:00.000Z",
  }),
  new Mentor({
    id: "mentor-26",
    user_id: "user-mentor-26",
    full_name: "Nina Petrov",
    email: "nina.petrov@idiap.ch",
    institution: "Idiap Research Institute",
    degree: "Doctorat",
    expertise: ["Conversational AI", "Prompt Design", "Evaluation"],
    bio: "Mentors projects involving language models, assistant design, and evaluation frameworks.",
    max_students: 6,
    created_at: "2026-03-26T13:35:00.000Z",
    updated_at: "2026-03-26T13:35:00.000Z",
  }),
  new Mentor({
    id: "mentor-27",
    user_id: "user-mentor-27",
    full_name: "Adrien Koch",
    email: "adrien.koch@uzh.ch",
    institution: "University of Zurich",
    degree: "Doctorat",
    expertise: ["Law and Technology", "Ethics", "Policy Analysis"],
    bio: "Supports students investigating legal, societal, and governance implications of technology.",
    max_students: 5,
    created_at: "2026-03-27T08:25:00.000Z",
    updated_at: "2026-03-27T08:25:00.000Z",
  }),
  new Mentor({
    id: "mentor-28",
    user_id: "user-mentor-28",
    full_name: "Sophie Lang",
    email: "sophie.lang@zhaw.ch",
    institution: "ZHAW",
    degree: "Master",
    expertise: ["Health Informatics", "Data Governance", "Process Design"],
    bio: "Mentors healthcare data projects with a strong focus on process quality and privacy.",
    max_students: 5,
    created_at: "2026-03-28T11:05:00.000Z",
    updated_at: "2026-03-28T11:05:00.000Z",
  }),
  new Mentor({
    id: "mentor-29",
    user_id: "user-mentor-29",
    full_name: "Gabriel Torres",
    email: "gabriel.torres@unisg.ch",
    institution: "University of St. Gallen (HSG)",
    degree: "Master",
    expertise: ["Business Analytics", "Decision Science", "Communication"],
    bio: "Helps students frame results clearly for both academic and business audiences.",
    max_students: 6,
    created_at: "2026-03-29T14:20:00.000Z",
    updated_at: "2026-03-29T14:20:00.000Z",
  }),
  new Mentor({
    id: "mentor-30",
    user_id: "user-mentor-30",
    full_name: "Alicia Romano",
    email: "alicia.romano@unibas.ch",
    institution: "University of Basel",
    degree: "Master",
    expertise: ["Service Innovation", "Customer Experience", "Applied Research"],
    bio: "Supports service-focused thesis projects with a strong applied and user-centered angle.",
    max_students: 5,
    created_at: "2026-03-30T09:55:00.000Z",
    updated_at: "2026-03-30T09:55:00.000Z",
  }),
];

